baseURL = "https://looseimpala.github.io/"
languageCode = "en-us"
title = "LooseImpala's Book Blog"
theme = "cactus"
enableEmoji = true


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2



[params]

  colortheme = "dark" # dark, light, white, or classic
